import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import { Providers } from "~/components/providers";
import { TRPCProvider } from "~/trpc/client";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body>
        <TRPCProvider>
          <Providers>{children}</Providers>
        </TRPCProvider>
        <Toaster />
      </body>
    </html>
  );
}
