import type { Metadata } from "next";
import "./globals.css";
import { Box, ClientOnly, Skeleton } from "@chakra-ui/react";
import { ColorModeToggle } from "~/components/color-mode-toggle";
import { Header } from "~/components/layouts/header";
import { Providers } from "~/components/providers";
import { TRPCProvider } from "~/trpc/client";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body>
        <TRPCProvider>
          <Providers>{children}</Providers>
        </TRPCProvider>
      </body>
    </html>
  );
}
